### ISSUE TITLE
Global highlight options

### ISSUE THREAD

**Issue by karlequin** [RolandPheasant/TailBlazer#102]
I quite like highlighting "error", "exception", "warning" etc., but I have to enter them every time I open a new file. Could we have a "global" checkbox for them in the search and highlight options dialog perhaps?

**Comment by RolandPheasant** [comment]
I have been considering this already, so yes.

**Comment by RolandPheasant** [comment]
@karlequin Job is done. If you build the latest you will get this.

![animation](https://cloud.githubusercontent.com/assets/9879866/15837830/daf95dc8-2c32-11e6-80f0-629b4938cb1d.gif)

Let me know how you get  one

**Comment by karlequin** [comment]
That's great, thanks!
