### ISSUE TITLE
Update chocolatey with v0.8

### ISSUE THREAD

**Issue by RolandPheasant** [RolandPheasant/TailBlazer#113]
@abuzhynsky there is a new release.

[v0.8.0.464](https://github.com/RolandPheasant/TailBlazer/releases/tag/0.8.0.464)

Could you update chocolatey please.

**Comment by abuzhynsky** [comment]
Sure. 
There is one issue though. Could you please recreate 0.8 release binaries archive without subfolder? We've already discussed it [here](https://github.com/RolandPheasant/TailBlazer/pull/73#issuecomment-187229272). 
I'll update package as soon as you fix it.

**Comment by RolandPheasant** [comment]
Ok. Will do it tonight

**Comment by RolandPheasant** [comment]
@abuzhynsky done

**Comment by abuzhynsky** [comment]
Done.

**Comment by RolandPheasant** [comment]
Thanks
