### ISSUE TITLE
Horizontal arrows scroll the wrong way

### ISSUE THREAD

**Issue by CADbloke** [RolandPheasant/TailBlazer#114]
Firstly, utterly awesome app and great example of the tools - **thank you**. I'm actually a little embarrassed about how trivial this issue is...

...when I click on the horizontal scroll arrows the screen scrolls in the opposite direction to what I expected. eg. In Notepad++ with word-wrap off the scrolling behaviour is opposite.

Yeah, that's all. Everything else is awesome.

Thanks again for this and all your work you share.

cheers
Ewen

**Comment by RolandPheasant** [comment]
I have to admit that issue is funny!

Luckily a trivial fix
