### ISSUE TITLE
 Ignore blank lines Option needed. 

### ISSUE THREAD

**Issue by JohannesSchmidt42** [RolandPheasant/TailBlazer#115]
In some logging scenarios there is an excess of blank lines that can't be suppressed upstream or are the product of some end of line conversion issues (like when piping adb with "adb locat > mylog.txt").  

It would be very convenient if TailBlazer could be told to ignore empty lines.

**Comment by RolandPheasant** [comment]
This should be quite easy so I will definitely do it

**Comment by RolandPheasant** [comment]
@JohannesSchmidt42 you will be pleased to know exclusion filters are now possible.  

You can exclude something by starting the search with a minus sign. In the following example I type "-", then the RegEx for a blank line. Use in Global tab to apply for all files, and Local tab for the current one only.

![exlude all blank lines](https://cloud.githubusercontent.com/assets/9879866/16130841/dc41a500-3402-11e6-93d1-04ef4a964bcf.gif)

**Comment by JohannesSchmidt42** [comment]
Thx! this works great. 
now i am left without any complaints... I can now start to spread the word and tell my colleagues to use TailBlazer
