### ISSUE TITLE
Invert search filter

### ISSUE THREAD

**Issue by gschizas** [RolandPheasant/TailBlazer#116]
There should be some kind of option to filter **out** some lines. There may be a way to do this with regular expressions (but it's not trivial). It would be better if there was a checkbox after each search filter to say that this specific filter should be inverted (i.e. lines matching that text or regex will be hidden).

Of course an invert filter should never be able to be highlighted (since those lines will be hidden anyway).

**Comment by Tiax** [comment]
My thoughts exactly, after starting to use the tool.

I think it's a very common use case to exclude lines that match a pattern, e.g. contain "DEBUG" loglevel or generally unimportant info.

**Comment by RolandPheasant** [comment]
I agree this will be very useful and is definitely on my list.

Creating exclusion filters will not be technically difficult. However the obvious use case of excluding lines with DEBUG or blank lines would require the exclusion to be applied to the All tab as well as other filters.

What has stopped me so far is other priorities plus I need to consider the ux and any performance implications.

**Comment by RolandPheasant** [comment]
Global filters and exclusions are available now. You can grab the latest build from 
[Latest Build](https://ci.appveyor.com/project/RolandPheasant/tailblazer/build/artifacts).

To exclude some text type "-" before the text to be excluded

![exlusion filters](https://cloud.githubusercontent.com/assets/9879866/16098901/3c5bf88e-334d-11e6-9bb4-061423dd5337.gif)
