### ISSUE TITLE
Add setting for always showing scroll bars

### ISSUE THREAD

**Issue by initram** [RolandPheasant/TailBlazer#126]
I work with some log files that do not update that often (once every 30 sec) and some of the lines in the log extends beyond the width of my log windows, so of cause I get a vertical scroll bar. This is all good.

The problem is when most lines are short and the top line (in the window) is long. When the next short line is logged it will try to remove the vertical scroll bar, making room for an extra line. This will then display the long line as the top most line, and it will then try to add the scroll bar to let me see the whole line. This all results in flickering between the two states.

So my suggestion is to allow us to always show the scroll bar, even when it is not needed.
Alternatively you can fix the flickering issue, but I am not sure how you would do that.

**Comment by RolandPheasant** [comment]
@initram I have been aware of this issue for some time and have been unable to implement a fix for the repeated measure which results in the horizontal scroll bar been repeatedly shown and hidden.

I feel daft that I have never thought just to always show the scrollbars.  I have just tried it and your suggested fix works.  

Until I find a proper fix, I have changed it so the scrollbars will always be visible
