### ISSUE TITLE
Highlighting for plain text "regex" not working

### ISSUE THREAD

**Issue by AlistairClark7** [RolandPheasant/TailBlazer#129]
Steps to reproduce

1. Enter search term that gets detected as regex in the "Type to search using plain text" input (e.g. "Name: Bob")
2. Click the .* button so the hint changes from "Hit enter to search using regex" to "Hit enter to search using plain text"
3. Hit enter in search box

The results get filtered correctly, but matches of "Name: Bob" are not highlighted.

**Comment by AlistairClark7** [comment]
It would be useful to be able to globally ignore searching for regex. Or a keyboard shortcut to override the auto detect and search via plan text. Happy to fork this and submit a pull request for this if that would be useful?

**Comment by RolandPheasant** [comment]
I will take a look at the issue next week. However I do recall there were some complexities of highlighting on regex so I had to programming in some caveats. I will get back to you on these details when I remember them.

If you feel you can improve this system please feel free to contribute. If you need help probably best to contact me on the gitter channel.

Thanks

**Comment by AlistairClark7** [comment]
Thanks, I will take a look around the code. After a bit more use it seems that only single word searches are being highlighted. But it's really nice so far!

**Comment by RolandPheasant** [comment]
Multiple words highlighting should work now in the latest master branch. Any issue reopen this
