### ISSUE TITLE
Follow Tail Jump

### ISSUE THREAD

**Issue by kfrancis** [RolandPheasant/TailBlazer#132]
I can't get a recording of it, but it's happened quite a few times where the output will continuously jump around while it attempts to follow the tail. It calms down once new entries are entered.

**Comment by RolandPheasant** [comment]
I think this is an issue which is solved but not released yet. It happens when a new line comes in which is wider than the viewable area. This forces the scroll bars to resize and this is turn scrolls up one and a loop starts.

Let me know if this is what you are seeing

**Comment by kfrancis** [comment]
That sounds about right. I'll check it out when the next release hits.

**Comment by RolandPheasant** [comment]
It's my second priority right now. I will let you know when it is done

**Comment by RolandPheasant** [comment]
This is solved in the latest build
