### ISSUE TITLE
Save Filters

### ISSUE THREAD

**Issue by kfrancis** [RolandPheasant/TailBlazer#134]
Since the log files will (more often than not) have the same keywords that you would filter by, it would be nice to be able to save those filters and apply when opening files in the same directory.

**Comment by RolandPheasant** [comment]
I have started a branch where I will enable global filters which are applied to all files.

Would that satisfy your requirement?

**Comment by kfrancis** [comment]
Absolutely!

**Comment by RolandPheasant** [comment]
Global filters are available now. You can grab the latest build from 
[Latest Build](https://ci.appveyor.com/project/RolandPheasant/tailblazer/build/artifacts)
