### ISSUE TITLE
Fine tune performance

### ISSUE THREAD

**Issue by RolandPheasant** [RolandPheasant/TailBlazer#14]
1. Scrolling can be sluggish on files which have a very large number of lines.  So far I have seen scrolling stutter on a file with 800k lines which was opened on a server share. In theory this can be solved by adjusting the scrolling sample rate, but in practice it is hard to predict when back pressures are formed. The idea solution would be for a task to run and if a queue has formed disregard all but the end of the queued job.

2. Some times there is a minor latency when opening a file.

3. Investigate whether the read algorithms can be improved

**Comment by GMTA** [comment]
+1 on the scrolling. It seems that the UI is updated every 500ms or so, while other tools update instantaneously.

Also, when heavy file update activity occurs, the application seems to hog 100% of one CPU core.

**Comment by RolandPheasant** [comment]
I have just been experimenting with indexing all the lines and have been able to achieve blisteringly fast scrolling. When the index is used I user stream.seek method to load the current page.

The largest file I have tested has 1.3 million lines and it scrolls very well. Of course the indexing adds to memory pressures but the experiment has shown me I am on the right track.

**Comment by GMTA** [comment]
You could reduce memory pressure by keeping a sparse index, e.g. indexing every 100th line instead of every line and using seeks for all lines in between. Doesn't have to be a constant, you can vary it by distance for example (index every line within 1000 lines of the current position, and decrease the resolution the further you go).

Alternatively, some tail tools (such as BareTail) give you the option to just keep the last X lines of the file in memory, discarding everything that falls off.

**Comment by RolandPheasant** [comment]
@oniony and I were also discussing some more sophisticated indexing options and there some overlap with our suggestion.  

You can be assured that fine tuning performance is my current priority
Thanks

**Comment by RolandPheasant** [comment]
@GMTA Its fast now check out this [Fast Scrolling] document (https://github.com/RolandPheasant/TailBlazer/blob/master/Documents/Fast%20Scrolling.md)

For super large files probably more work required but for now I am going to put my feet up

**Comment by GMTA** [comment]
@RolandPheasant I tried the latest release but it isn't able to read my log files correctly. Lines are garbled and distorted, sometimes beyond recognition. They are fairly standard WildFly log files.

So I'm not really able to test your changes. However, it does seem like the UI updates every 500ms making it a somewhat slow experience compared to other tail tools like Baretail.

**Comment by RolandPheasant** [comment]
I just spotted that . Seems to be the way I have calculated the line lengths when indexing the file.  I am on the case. Is it possible to attach as smallish  extract here so I can test the indexing on your file type.

**Comment by RolandPheasant** [comment]
@GMTA I think I have worked out the issue for both problems. Should be able to get a fix out in a day or 2.

**Comment by RolandPheasant** [comment]
@GMTA the files should decode correctly now.

**Comment by GMTA** [comment]
Decoding seems to be fixed, great work! Tailblazer seems very CPU bound at the moment, it barely responds when other applications are taxing my CPU at the same time, even for small log files.

**Comment by RolandPheasant** [comment]
Thanks for that.  I suspect the underlying problem is network latency coupled with too fast a poll interval.  I am looking in work at an active 1.3 M line log file (100 MB in size) over a network share and my cpu is doing almost nothing

So to address the issue I will: 

a) slow down the poll rate
b) rather than polling on a schedule, poll and allow for inactivity before polling again

I suspect in your instance the time it takes to check for changes and subsequently load the changes is longer than the polling interval leading to an ever growing queue of updates.  I will add a load of logging  soon.

**Comment by RolandPheasant** [comment]
@GMTA I have raise issue #30 to deal this this one and will be opening issues specifically for different performance problems. I will let you know when that is done

**Comment by GMTA** [comment]
Alright, but just to make sure: my log files are locally accessed, not over a network share.

**Comment by RolandPheasant** [comment]
Blimey!  I will add a load of more logging to help get to the bottom of this.

**Comment by RolandPheasant** [comment]
Again thanks for the input

**Comment by RolandPheasant** [comment]
@GMTA I have done lots of work on performance and found a few issues clearly slowed things down.  The latest release (see [v0.2.2](https://github.com/RolandPheasant/TailBlazer/releases/tag/0.2.2)) should be a lot quicker.  I would appreciate if you take a look.

At the weekend I will be doing a release which according to my tests should be highly performing even for gigabyte sized files.

**Comment by GMTA** [comment]
@RolandPheasant Performance has improved! I'll be testing some more tomorrow.

**Comment by RolandPheasant** [comment]
:+1: Thanks for checking. Someone in work just showed me a folder full of 20 Gigabyte sized files so handling files that size has become my new challenge.

**Comment by RolandPheasant** [comment]
@GMTA  [version 0.3](https://github.com/RolandPheasant/TailBlazer/releases/tag/0.3) should be much much better. Please try and let me know how it goes.

**Comment by GMTA** [comment]
I've been testing version 0.5 and there are two major issues in the way it handles tailing my log files:
* CPU usage is maxing out on a moderately updated log file (<1 MB, regular line length)
* Sometimes the UI seems to "hang" on a new line, becoming jittery and resuming normal operation after about half a second. This also happens when scrolling through files without updates happening.

**Comment by RolandPheasant** [comment]
The only time I have seen performance suffer is when there are very long lines in the log file. Is this the case for you? Is so then I am aware of the issue.

Is it possible for you to upload a sample file here so I can open it on my machine, or is the content sensitive?

**Comment by RolandPheasant** [comment]
@GMTA My suspicion was correct.  I generated a file with lines which are greater than 10kB each and Tail Blazer ground to a halt

Now I know what the issue is I will work out a solution
