### ISSUE TITLE
Exclude and filter on the same text produces unexpected results

### ISSUE THREAD

**Issue by rcince** [RolandPheasant/TailBlazer#141]
Noticed that when I exclude text (i.e. "-info") and move that to a global exclusion and then filter on that same text, but not as an exclusion, all instances appear. Also, in settings, the info filter shows up in both the global and local scope (as if there are really two filters) but there is only one tab for. 

I'd have expected to not see any lines containing "info" because it is a global exclusion and for both filters to appear in the Switch Results tab. I will try and look at this if I can find time in the coming weeks.

**Comment by RolandPheasant** [comment]
I have set it up that whatever is in the local overrides what is in the global. This enables intentional local overrides

Also note that adding a search / exclusion is case sensitive meaning info and INFO and be added at the same time.

That said, a) I fixed a couple bugs about an hour or two ago b) I will look into it

**Comment by RolandPheasant** [comment]
@rcince could you grab the release from [v0.9.0.536](https://github.com/RolandPheasant/TailBlazer/releases/tag/0.9.0.536) and try again. Thanks

**Comment by rcince** [comment]
Ah, I see. That makes total sense now that I've considered intentional local overrides. 
I've had a scan over 0.9.0.536, but I'm not sure what's happening here (the filter tabs aren't appearing): 

![Screencast](http://i.imgur.com/XDF0nvy.gif)

Great app thought!

**Comment by RolandPheasant** [comment]
Select the filter check box for new tabs

**Comment by rcince** [comment]
Done some more testing and it appears to only be a problem when adding filters via the "Search and highlight options" dialog. See below

![](http://i.imgur.com/lJWnGKl.gif)

**Comment by rcince** [comment]
Overlooked that. Fantastic!

**Comment by RolandPheasant** [comment]
Yeah.  Sound like it works for yoy
