### ISSUE TITLE
Update Chocolately

### ISSUE THREAD

**Issue by RolandPheasant** [RolandPheasant/TailBlazer#142]
@abuzhynsky there is a new release.

[v0.9.0.536](https://github.com/RolandPheasant/TailBlazer/releases/tag/0.9.0.536)

Could you update chocolatey please.

**Comment by abuzhynsky** [comment]
@RolandPheasant I've packed and uploaded new version to chocolatey feed. Waiting for moderator approve.

**Comment by RolandPheasant** [comment]
Thanks
