### ISSUE TITLE
It is possible to open the same file multiple times

### ISSUE THREAD

**Issue by nmummau** [RolandPheasant/TailBlazer#143]
Current version: v0.9.0

1. Open a file in Tail Blazer
2. Click the hamburger menu in the top left of the app
3. Under 'Recent Files' click on the file that you just opened in step 1.

BUG: now you have two tabs open in Tail Blazer with the same file open.

![image](https://cloud.githubusercontent.com/assets/10524529/16155802/07710f6e-347f-11e6-9975-e749015f96bd.png)

**Comment by RolandPheasant** [comment]
That is by design as it enables comparing different filters on the same file side by side
