### ISSUE TITLE
Switching files while the 'Search and highlight options' dialog is open doesn't update the dialog

### ISSUE THREAD

**Issue by nmummau** [RolandPheasant/TailBlazer#145]
1. Open two different files (e.g. File1 an File1)
2. Click on the File1 tab to view it
3. Click the gear icon at the top right to open the 'Search and highlight options' dialog
4. Setup a few filter/highlighting rules under the 'Local' scope
5. At the top of the application, click on File2. 

**BUG**: the context of the dialog still shows the Local filter/highlighting rules that you setup for File1. This dialog should switch to show you the Local filter/highlighting rules of File2 after switching in step 5.

**Comment by RolandPheasant** [comment]
@nmummau I have fixed this by closing the dialog when selection is switched
