### ISSUE TITLE
Match whole word only should be a setting of the 'Search and highlight options'

### ISSUE THREAD

**Issue by nmummau** [RolandPheasant/TailBlazer#146]
Current version:
v0.9.0

Feature request: 
It would be nice if you could setup the 'Search and highlight options' to match whole word only. I have a rule setup to highlight the word 'add' but the highlighting is a bit noisy due to this missing feature.

My rule:
![image](https://cloud.githubusercontent.com/assets/10524529/16157668/790a9480-3487-11e6-97cc-65f49d91998c.png)

Noisy highlighting in my log:
![image](https://cloud.githubusercontent.com/assets/10524529/16157660/740020b8-3487-11e6-96dd-9aea33f7222f.png)
![image](https://cloud.githubusercontent.com/assets/10524529/16157712/bde7bb78-3487-11e6-8b95-cc09c10d2c3e.png)

**Comment by MattFloyd** [comment]
Try using a regular expression and typing `\badd\b` for a word boundary

**Comment by nmummau** [comment]
Thanks MattFloyd, you're awesome! That worked for me!

![image](https://cloud.githubusercontent.com/assets/10524529/16158024/3f969198-3489-11e6-9491-2d0d597e2495.png)

**Comment by RolandPheasant** [comment]
@MattFloyd great call. I probably would not have thought of that.
