### ISSUE TITLE
Filter Include / Filter Exclude

### ISSUE THREAD

**Issue by ckarcz** [RolandPheasant/TailBlazer#147]
# Have two filtering types:

**Filter Include** - Only logs containing the filter string will be included in the logging window. Use case would be "I only want to see logs about Foo" (already implemented in TailBlazer as the only filtering type).
**Fliter Exclude** - Logs containing the filter string will be excluded from the logging window. Use case would be to filter out things you don't want to see ("I don't want to see DEBUG logs, or logs about Foo".

**Comment by RolandPheasant** [comment]
Check out exclusions filters here https://github.com/RolandPheasant/TailBlazer/wiki/Release-v0.9. Already possible
