### ISSUE TITLE
Wrong tab selected after opening log file from Windows Explorer

### ISSUE THREAD

**Issue by barser** [RolandPheasant/TailBlazer#152]
For example, if I have several log files opened in previous session of TailBlazer and then I double clicked on another log file in Windows Explorer, TailBlazer opens this file in new tab, but this tab is not in focus. It's rather uncomfortably.

See screenshot:
1. Open several files in TailBlazer (unifond_20160706.log, unifond_20160705.log)
2. Close TailBlazer.
3. Double click on unifond_20160704.log. TailBlazer will be opened with three tabs - unifond_20160704.log, unifond_20160705.log, unifond_20160706.log and the last tab will be active, but it is desired to activate tab with file on which I double clicked.

![2016-07-06_11-29-56](https://cloud.githubusercontent.com/assets/8071147/16611944/0648cfc6-436d-11e6-8c20-fee4432aa6d8.png)

**Comment by barser** [comment]
Maybe adding an option to close all tabs when closing TailBlazer will be helpful!

**Comment by MrCull** [comment]
This issue does not appear to be as simple to resolve as it first sounded. Perhaps someone intimate with the code base might be able to offer a few pointers.

Also agree the second separate feature to not always open old tabs would be a useful feature (for the way I generally use the tool). So this is perhaps worth raising as a separate issue?

Awesome tool btw!

**Comment by RolandPheasant** [comment]
@barser @MrCull  I think I can solve this by waiting for the previous files to be restored, then opening the file which was passed through to the command line args

@MrCull thanks for the appreciaton.

Also I am been giving TB a rest lately as a) it is summer and b) I have been giving lots of love to [Dynamic Data](https://github.com/RolandPheasant/DynamicData) which is the project which I consider to be my main os project (even though it is not proving to be as popular as Tail Blazer!

However I will be picking it up this week or next week and have loads of planned features

**Comment by MrCull** [comment]
No problem - I had a look for modern tail type apps a little while back and this one appeared pretty decent. Actually this one was perfect as it was light weight, portable, OS, plus it works great too.

In the organisation I work for we produce a range of semi bespoke and other more generic server based business critical systems. Many of these have dedicated support agreements with very tight SLA times. The systems write trace to text log files and therefore being able to monitor these on the fly is always a great help.
I intend to start spreading the word about this app so thanks for all your effort in making it so far :-)

If you want to log any new possible new features with a design spec as in Issue then I might have a go implemented one or two myself depending if I get the spare time and complexity.

Also I'll raise a separate issue for the comments above regarding having an option to not open previous files on start up as that will be a useful feature for me.

**Comment by RolandPheasant** [comment]
@MrCull thanks for the positive words.  I always enjoy knowing that people out there are appreciation the fruits of my labour, One thing I need to correct you on is that alas TB is not portable! Maybe one day.

As for helping with issues, I should be getting some momentum back into TB next week and will consider my to do and features list. I will notify you when I prioritise this.

**Comment by michaeldaw** [comment]
My team and I have been using Tailblazer for a while and really like it. It's a great evolution of the typical tracing app. However, this particular issue has become something of a problem.

When double-clicking on a file in Explorer, one expects that file to open in the assigned application. Said another way: people assume the file they are looking at is the file they double-clicked on. In Tailblazer, however, this is not the case.

On several occasions people have found themselves examining out of date log files (and taking actions based on them) because they assumed, incorrectly, that they were looking at the file they attempted to open in explorer.

**Comment by Beguiled** [comment]
I don't see how this is the fault of TailBlazer. Can you be more specific and give and example of the steps taken that leads to your team's outcome?

**Comment by Beguiled** [comment]
Nevermind. I misunderstood the comment.

**Comment by michaeldaw** [comment]
Apologies. I didn't mean to blame anyone. The steps we undergo are the same as those outlined in the original post for this issue. While it may be somewhat fundamental to the software, as MrCull mentioned, it seems somewhat counter-intuitive to double-click a particular file in Explorer, and to then be initially viewing a different file when Tailblazer launches.

**Comment by MrCull** [comment]
Agree with @michaeldaw and this is closely related to #160

Unfortunately I have not had time myself again yet to look at implementing this :-(
Also it would be great to get some guidance from @RolandPheasant for screen designs on #160

**Comment by RolandPheasant** [comment]
I am on holidays this week. Will respond next week

**Comment by t0mburton** [comment]
Hi @RolandPheasant 
When you have a spare moment could you check out the above commit, this solves the issue described here. If you are happy with the solution I will create a PR.

I'm becoming more familiar with the code base so will submit a PR for [#16](https://github.com/RolandPheasant/TailBlazer/issues/160) soon.

**Comment by RolandPheasant** [comment]
That looks straight forward. Feel free to raise it as a PR
