### ISSUE TITLE
Horizontal scroll bar misbehaving when clicking in track

### ISSUE THREAD

**Issue by drewnoakes** [RolandPheasant/TailBlazer#157]
Firstly I'm excited about using this log viewer. Thanks for all your work on it so far!

This one's pretty minor and hopefully as minor to fix.

- Ensure you have a log line that's wider than the window
- Move the horizontal scroll bar thumb midway across the track
- Click in the track (between the thumb and the arrow)

For me, on the right hand side, nothing happens. On the left hand side, the thumb actually moves right.

The vertical scroll bar behaves as you'd expect.

**Comment by RolandPheasant** [comment]
Thanks for the appreciation. 

Are you using version 9?

**Comment by drewnoakes** [comment]
Yep, 0.9.0.

**Comment by drewnoakes** [comment]
We're you able to fix this?

**Comment by RolandPheasant** [comment]
Yes.  Fixed by @MrCull

**Comment by drewnoakes** [comment]
Nice, cheers.
