### ISSUE TITLE
App opens in center then jumps to last opened position

### ISSUE THREAD

**Issue by nnpcYvIVl** [RolandPheasant/TailBlazer#167]
When opening the app it initially appears in the center of the screen then jumps to its last opened position. Can you fix it to open directly to the last opened position?

**Comment by nnpcYvIVl** [comment]
Screengrab of issue.

[TailBlazer - App opens in center then jumps to last opened position.zip](https://github.com/RolandPheasant/TailBlazer/files/664858/TailBlazer.-.App.opens.in.center.then.jumps.to.last.opened.position.zip)

**Comment by RolandPheasant** [comment]
I know of this and will take a look when I get a chance
