### ISSUE TITLE
SSH/SFTP Support for Tailing Remote Files

### ISSUE THREAD

**Issue by ivanatpr** [RolandPheasant/TailBlazer#20]
Not sure how feasible this is but it would be really neat to have the ability to tail files on a remote server via SSH and/or SFTP. Most log files that I'm interested in tailing live in remote unix servers.

**Comment by RolandPheasant** [comment]
I know there are several c# ssh clients out there so in theory possible. However to make it work I would need do be able to stream the file over the connection, If this can be done then I will do it.

However this would not be my immediate priority.

**Comment by ivanatpr** [comment]
Not sure how much support SSH libraries will have for file events, but one (potentially hacky) approach is to literally run "tail -f <file>" on the remote server and then stream the output. Perhaps even stream the output directly to a local file in a temp dir such that the main TailBlazer process can then open it just like any other local file. Just a thought.

**Comment by RolandPheasant** [comment]
That should in theory work

**Comment by RolandPheasant** [comment]
This will be considered in #51
