### ISSUE TITLE
Tail file even after it has been newly created

### ISSUE THREAD

**Issue by wmaurer** [RolandPheasant/TailBlazer#22]
Both nlog and log4net have the concept of rolling log files, where based on a certain condition (file size, time of day), the log file is archived, and a new 'current' log file is created.
I assume in this case the 'current' log file is renamed, and a new 'current' file is created, with the same name, e.g.
```
Web.Server.SignalR.201511180800.log
Web.Server.SignalR.201511180830.log
Web.Server.SignalR.log <-- current
```
However when I tail the 'current' log file, TailBlazer stops tracking changes after the rollover has occurred.

Another non-modern application (baretail) does this correctly. It would be great if TailBlazer could also do this.

**Comment by RolandPheasant** [comment]
I have accounted for the rollover but there currently is a bug.

In my testing I just manually delete the the log file to simulate rollover. However when the logger does this nothing happens!

As this is bread and butter logging functionality I will try and fix this after work tonight

**Comment by oniony** [comment]
It's probably because the logging library renames the file, rather than deleting it. If it were to delete the file then any tool that is currently reading it would potentially error. By renaming the file, those open streams are unaffected.

The file rename should trigger a `Renamed` filesystem notification, however, that you could listen for.

**Comment by GMTA** [comment]
+1 Renames are currently followed, which is not the expected behavior

**Comment by RolandPheasant** [comment]
Should work now

**Comment by wmaurer** [comment]
:+1: Thanks, I can confirm it's now working as expected.
