### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by wmaurer** [RolandPheasant/TailBlazer#23]
TailBlazer needs a tasty :yum:  application icon so that it looks nice when pinned to the taskbar ;-)

Insipiration?
https://www.iconfinder.com/icons/197416/fairy_fairy_tail_tail_icon
https://thenounproject.com/search/?q=tail
http://bit.ly/1X8hl4t

**Comment by RolandPheasant** [comment]
An icon is a must see [#15](https://github.com/RolandPheasant/TailBlazer/issues/15).

I quite like this [comet icon](https://icons8.com/web-app/11451/comet).  Would be good to see what it looks like in the tray

**Comment by wmaurer** [comment]
Sorry, I hadn't seen issue #15. I recommend closing this and continuing on #15.
