### ISSUE TITLE
Please put this app to the Windows 10 Store!

### ISSUE THREAD

**Issue by alexsorokoletov** [RolandPheasant/TailBlazer#25]

**Comment by RolandPheasant** [comment]
This relates to issue [#12](https://github.com/RolandPheasant/TailBlazer/issues/12)

This is a new project so alas have not had time to package the beast yet. My current priority is to achieve high performance for large files which should be ready shortly after the weekend.

After that I will consider where to deploy. However unfortunately windows 10 store is out of reach as WPF apps are current not allowed. 

btw I appreciate your enthusiasm

**Comment by alexsorokoletov** [comment]
:+1:  Maybe if you put the logic to the PCL then you will be able to abstract from WPF/Desktop .NET
This is really useful tool and I would love to have it installed and used on my machine

**Comment by RolandPheasant** [comment]
MS have stated a wpf app is the recommended desktop application for new projects. They have also promised wpf will be permitted in the app store but so far that has yet to materialise.

As for a portable version then I would be happy to do that when this  https://github.com/ButchersBoy/MaterialDesignInXamlToolkit works on universal apps.

All that said, a chocolatey package will make it installable for you. Alternatively for now you can grab the binaries from here https://github.com/RolandPheasant/TailBlazer/releases

**Comment by DoCode** [comment]
Nonono... Microsoft says WPF is THE Windows Desktop technology.
We should not go to the other ways. Then better we wait for the Microsoft Windows WPF/WinForm/Win32 Bridge for the Store

**Comment by RolandPheasant** [comment]
TailBlazer is on chocolatey and for at least the medium term will exist there only
