### ISSUE TITLE
Crashes when I open a log

### ISSUE THREAD

**Issue by oniony** [RolandPheasant/TailBlazer#31]
I've tried to open a variety of log files of various sizes using drag-drop and the menu option but Tail Blazer crashes every time.

Here's the entry from the event viewer:

    Fault bucket , type 0
    Event Name: CLR20r3
    Response: Not available
    Cab Id: 0

    Problem signature:
    P1: TailBlazer.exe
    P2: 0.2.1.91
    P3 :565377bc
    P4: PresentationFramework
    P5: 4.5.27.0
    P6: 545cb089
    P7: 2b7d
    P8: 215
    P9: System.Windows.Markup.XamlParse
    P10: 

    Attached files:
    C:\Users\ME\AppData\Local\Temp\WER9C05.tmp.WERInternalMetadata.xml

    These files may be available here:
    C:\Users\ME\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_TailBlazer.exe_7242bbd390b4a3e70eeb19c5a816bd8c2b82651_ba3fa94e

    Analysis symbol: 
    Rechecking for solution: 0
    Report Id: cca1fc0e-9299-11e5-92cb-7446a0a3e8d8
    Report Status: 1

**Comment by RolandPheasant** [comment]
Do you have .net framework 4.6 installed?

**Comment by oniony** [comment]
No I have 4.5, 4.5.1 and 4.5.3 preview.

The weird thing is it actually runs and then only crashes when I try to open a file. Wouldn't it not work at all if it was a .NET version problem?

**Comment by RolandPheasant** [comment]
Does C:\Users\ME\AppData\Local\Temp\WER9C05.tmp.WERInternalMetadata.xml give you any clue?

**Comment by RolandPheasant** [comment]
It is built for dot net 4.6. Is it possible for you to try installing it?

Also there is probably no need for me to build to 4.6. I will downgrade it to 4.5 and if all is fine keep it there

**Comment by oniony** [comment]
Works now, thanks.
