### ISSUE TITLE
File encoding incorrect for log produced by batch file with accented characters included.

### ISSUE THREAD

**Issue by guygervais** [RolandPheasant/TailBlazer#33]
[InventairePerpetuel.txt](https://github.com/RolandPheasant/TailBlazer/files/42880/InventairePerpetuel.txt)

**Comment by RolandPheasant** [comment]
Thanks for this

**Comment by RolandPheasant** [comment]
Thanks again. I can now see where the error lies and I am on the case. Without the file I would have no idea

**Comment by guygervais** [comment]
Glad I could help.

De : Roland Pheasant [mailto:notifications@github.com]
Envoyé : 24 novembre 2015 13:24
À : RolandPheasant/TailBlazer
Cc : Guy Gervais
Objet : Re: [TailBlazer] File encoding incorrect for log produced by batch file with accented characters included. (#33)


Thanks again. I can now see where the error lies and I am on the case. Without the file I would have no idea

**Comment by RolandPheasant** [comment]
@guygervais I have fixed this one. Could you try again with the latest release or build and let me know

**Comment by guygervais** [comment]
Works great. Even better than BareTail now, since the diacritics show up correctly.

Thanks!

Guy

De : Roland Pheasant [mailto:notifications@github.com]
Envoyé : 29 novembre 2015 11:01
À : RolandPheasant/TailBlazer
Cc : Guy Gervais
Objet : Re: [TailBlazer] File encoding incorrect for log produced by batch file with accented characters included. (#33)


@guygervais<https://github.com/guygervais> I have fixed this one. Could you try again with the latest release or build and let me know

**Comment by RolandPheasant** [comment]
:+1:  The next release which should be in less than a week will also mean that Tail Blazer can easily handle giga byte files. After that I will start enriching it with loads of features
