### ISSUE TITLE
Log not rendering

### ISSUE THREAD

**Issue by Echarnus** [RolandPheasant/TailBlazer#38]
I encountered a bug where the TextBlock (?) doesn't want to render unless it overflows and a scrollbar appears (screenshots 0 and 1). 

When starting from a log file which doesn't contain entries, I even had to reopen the file (screenshot 2).

![tailblazer-not-rendering-log-bug-0](https://cloud.githubusercontent.com/assets/9265969/11456284/fb50e6f2-9684-11e5-8e9a-7e39e5da0cda.PNG)
![tailblazer-not-rendering-log-bug-1](https://cloud.githubusercontent.com/assets/9265969/11456282/fb4ea41e-9684-11e5-87c4-46a6e3c4b933.PNG)
![tailblazer-not-rendering-log-bug-2](https://cloud.githubusercontent.com/assets/9265969/11456283/fb4f8a32-9684-11e5-9fb0-37465ef00e94.PNG)

Note: This is from the build of the release page. Not a build I made myself.

**Comment by RolandPheasant** [comment]
This should be fixed in the next release which should be going out today.  I will let you know when it is done

**Comment by RolandPheasant** [comment]
@Echarnus this should now work in version 0.2.2
