### ISSUE TITLE
Pass arguments through command line

### ISSUE THREAD

**Issue by ForNeVeR** [RolandPheasant/TailBlazer#43]
I would like to call `TailBlazer C:\logs\file.log` and have it open the file immediately after the start.

**Comment by RolandPheasant** [comment]
Good suggestion

**Comment by Echarnus** [comment]
Will this enable to open files immediately from the file explorer with TailBlazer? Because I've noticed the application started but the file didn't open.

**Comment by RolandPheasant** [comment]
That sounds like a bug to me.

**Comment by Echarnus** [comment]
Sorry for the late reaction. Tested it out with the newest build (v0.5245) and I still got that problem. My OS is Windows 8 SP1. Got the same problem at Windows 10. Default application set to Tail Blazer of course.

**Comment by RolandPheasant** [comment]
Just got it working on my computer. Will be in the next release

At some point I will include some file association options as part of TailBlazer
