### ISSUE TITLE
Open pipe instead of file

### ISSUE THREAD

**Issue by ForNeVeR** [RolandPheasant/TailBlazer#44]
It would be very nice to pipe command output to TailBlazer and use it as a log viewer (as a real `tail` program). For example,

```
cmd> nginx | TailBlazer
```

(`nginx` here is just an example of a long running application)

It would be even more nicer to connect to any running process stdout and read its logs, but I fear that it will involve much native code magic and dealing with Windows permissions; maybe it isn't possible at all.

**Comment by RolandPheasant** [comment]
Any command output in theory could be piped to tail blazer using stand command output parsing. 

My first instinct is this is doable but will require further research.

**Comment by RolandPheasant** [comment]
This will be considered in #51
