### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by ForNeVeR** [RolandPheasant/TailBlazer#45]
There definitely should be a possibility to copy a piece of log to the clipboard.

**Comment by RolandPheasant** [comment]
Someone in work just asked me for that

**Comment by ForNeVeR** [comment]
It wasn't me :)

**Comment by RolandPheasant** [comment]
Actually 2 people have asked me in work and now you. This will be first job when I have finished work on large file handling (almost there now)

**Comment by RolandPheasant** [comment]
@ForNeVeR  This has been a surprisingly tricky task since the log entry lines are virtualised and as soon as an item is scrolled out of view it is out of memory.

To get around this difficulty I have had to create a controller to monitor selected items and store items which have recently been removed from the view. This is to ensure that you can select an item, scroll down, and press shift to multi-select a range starting at the first selection.

Although I have tested it I would appreciate you give it some extra scrutiny.

Thanks

**Comment by ForNeVeR** [comment]
I knew it would be a tricky because of how you handle the text stream, so no worries, we'll get it sorted. It's very cool  that you've done it. Some issues I've noticed:

1. Mouse selection would be cool. I think that simple text selection with mouse gesture should be available, so I could move my mouse with the button clicked to select multiple lines of text.
2. Ctrl-A works okay (well, we cannot select the whole file, so let's select the visible area, I'm okay with that idea), but Shift-selection after Ctrl-A is not:
    - Press Ctrl-A
    - Scroll up a couple lines
    - Press shift and click any line above your selection. What I expect is that the selection will be expanded to this line. What I get is the selection gets expanded by 1 line up.

    I am sorry if my explanation is messy, please try that and I think you'll notice the problem easily.
3. While reproducing the problem *2*, somehow I got this:
   
   ![image](https://cloud.githubusercontent.com/assets/92793/11721043/0df09fc2-9f8c-11e5-8a09-5970841ab34b.png)

   If I scroll up or down, all the lines between the selected regions gets highlighted as "selected", so I assume that I really have 14 lines selected there. But when I copy-pasted these lines, I got 15 lines in my clipboard (the 14 highlighted and one below them); that quickly became very messy so I give up researching this.

If it would be preferable, I could file a separate issues for every problem I've encountered.

**Comment by RolandPheasant** [comment]
Re: mouse selection, I agree it is a must. It is something which at this stage I have not worked out how to do it. Maybe there is just some property to set on the ListBoxItemContainer.

I will have a look at the CTL-A issue tomorrow,I think I will have to add specific logic for it.  The gap the in the files is probably a hang up from a state before the ctl-a command was invoked.

Also if you grab the 'FindInFile' branch I have added a debugging status bar which gives the selected items count - this is useful when debugging the copy paste stuff.  With this you will also see my first attempt at enabling multiple searches - I want to expand it so a user can easily enter text, hit enter to search and click 1 button to be able to see extra options like text highlighting colours, altering  etc...

Let's keep to this issue for all copy paste related matters.

**Comment by RolandPheasant** [comment]
@ForNeVeR It should be a lot better now. Also got the mouse selection thing working. Would you like to build and try again.

Btw: check out the image [here](https://github.com/RolandPheasant/TailBlazer) as mult-searching can now be done
