### ISSUE TITLE
Progress symbol

### ISSUE THREAD

**Issue by wmaurer** [RolandPheasant/TailBlazer#49]
Since TrailBlazer now has an icon, the next idea is for a [progress symbol](https://github.com/RolandPheasant/TailBlazer/pull/48#issuecomment-162237848).

This issue is the starting point for the next PR.

Possible inspiration, an animated version of:
https://icons8.com/web-app/11451/comet

**Comment by RolandPheasant** [comment]
That would be awesome.  I like the Git hub symbol with the circular spinning thing around the octo-cat. Something similar to that would be great but perhaps even better for something creative and original. For example the comet symbol where the tail has fire coming from it (in the highlight colour).

I am open to ideas.

**Comment by wmaurer** [comment]
The circular spinning thing in the style of github's wouldn't be too hard. Here's a link to it:
![octocat-spinner](https://assets-cdn.github.com/images/spinners/octocat-spinner-128.gif)

My approach would be to modify the ControlTemplate of the WPF ProgerssBar.
I'll have a look at it at some time this week

**Comment by RolandPheasant** [comment]
If you can to that it will be great. Changing the control template / style of the progress bar is definitely the way forward.  

My limitation is I am not very good (I need to learn!) at doing paths / animations in WPF

**Comment by thoemmi** [comment]
[LoadingIndicators.WPF](https://github.com/100GPing100/LoadingIndicators.WPF) offers many different spinners, and they claim to support MahApps.Metro too.

**Comment by RolandPheasant** [comment]
@thoemmi  I am currently using  this [Spinner](https://github.com/RolandPheasant/TailBlazer/blob/master/Images/SpinnyThingWhenLoading.gif)  which is a proress bar from MaterialDesignToolKit. However I think it would be a real nice touch to some Tail Blazer specific spinner.

**Comment by RolandPheasant** [comment]
@thoemmi btw those in you link to look good

**Comment by RolandPheasant** [comment]
@wmaurer probably best to base the spinner on the MaterialDeisgnToolKit one, with the comet in the centre.  This will keep it consistent with the whole material design style of Tail Blazer
