### ISSUE TITLE
Save and restore window size and position

### ISSUE THREAD

**Issue by kmcginnes** [RolandPheasant/TailBlazer#52]
The windows size and position should be restored every time I launch the app. Phil Haak has a great [example of this](http://haacked.com/archive/2012/04/09/reactive-extensions-sample.aspx/) using Rx.

**Comment by RolandPheasant** [comment]
Tail blazer is using dragablz which is a fully fledged docking library. It also has the google chrome capability of pulling a tab out into and independent window.

I work with the guy who created it so I will ask if there is any sample store / restore code to use as a starting point

**Comment by RolandPheasant** [comment]
@kmcginnes It's been a while this is done now.

**Comment by kmcginnes** [comment]
Haha. I'm sorry man. I got caught up in some other things and never got back to this. I'll download the latest and check it out.

**Comment by RolandPheasant** [comment]
No problem. It is been something I had been meaning to do for a very long time os happy to have it done now
