### ISSUE TITLE
Select text in search results

### ISSUE THREAD

**Issue by MendelMonteiro** [RolandPheasant/TailBlazer#55]
Copying values from filtered results is a classic use case

**Comment by RolandPheasant** [comment]
@MendelMonteiro  In the un-released version, you can copy selected rows to the clipboard using ctl-c or the right click context menu (there are one or 2 bugs still)

Also I am working on a simple viewer for viewing a filtered line in position in the  original file. 

These 2 will give you all the full range of select / copy options

**Comment by MendelMonteiro** [comment]
Great to hear you had this in mind already!

**Comment by RolandPheasant** [comment]
I have the first cut done.  Check out the image on the Tail Blazer homepage.

If you want to try / test  it just build from the latest code
