### ISSUE TITLE
Select characters within a result line (filtered or inline)

### ISSUE THREAD

**Issue by MendelMonteiro** [RolandPheasant/TailBlazer#58]
When one wants to select a word or chars from a specific result line currently it's necessary to copy the line into a text editor and then copy the desired text.  It would be great to do this directly from TailBlazer.

**Comment by CasperTDK** [comment]
+1

**Comment by RolandPheasant** [comment]
I have encountered exactly the same use case when using Tail Blazer.

What I propose is to have a text mode which when enabled will change what is displayed into rich text. This would also for selected text highlighting.

**Comment by CasperTDK** [comment]
Hmm, maybe, but speed is my primary concern. So I do not want to select a line, active rich text and then select the value.

Preferably I would just double click on '49' on this line and it is selected:

"System.Web.HttpCompileException (0x80004005): c:\Projects\RegionMidt-CMS\Source\Mediaworkers.RM.Internet\Views\Shared\Layout\_Footer.cshtml(49): error CS1502: The best overloaded method match for 'System.Web.WebPages.WebPageExecutingBase.Write(System.Web.WebPages.HelperResult)' has some invalid arguments"

That would be good behaviour :)

**Comment by RolandPheasant** [comment]
If I will get my thinking hat on

**Comment by CasperTDK** [comment]
The more I think about, I would probably expect the behaviour to be bound to 'double-click'
So if you double click, the mark the selected word or value (space being the delimiter).
