### ISSUE TITLE
Inline view scroll position randomly reset

### ISSUE THREAD

**Issue by MendelMonteiro** [RolandPheasant/TailBlazer#59]
When showing search results with the inline view enabled I have noticed that if you scroll in the inline view after a short delay (a couple of seconds) the inline view will scroll back to it's original position.

**Comment by RolandPheasant** [comment]
This is fixed in dev. The will merge the branches tonight

**Comment by MendelMonteiro** [comment]
Man, your issue resolution response time leaves nothing to be desired...

**Comment by RolandPheasant** [comment]
I had previously done the fix (I think). Can't do the merge as there are a couple outstanding issues.

However if you want a quick look at the new features including zoom and dark / light themes you can grab the branch ThemeAndOption and build it  yourself. The new options are on the hamburger menu

**Comment by RolandPheasant** [comment]
@MendelMonteiro could you try aha in on the latest build or release and let me know if it is fixed

**Comment by RolandPheasant** [comment]
Any problems, reopen this issue

**Comment by MendelMonteiro** [comment]
Will do in the new year as I'm away till then

**Comment by RolandPheasant** [comment]
:+1:

**Comment by MendelMonteiro** [comment]
I've just pulled and rebuilt on the master branch and still see the same behaviour

**Comment by RolandPheasant** [comment]
Would it be possible for you to capture this behaviour using screentogif? Then I would be able to see what you mean.

**Comment by MendelMonteiro** [comment]
![tailblazer inline scroll reset](https://cloud.githubusercontent.com/assets/1752566/12090011/052eb276-b2eb-11e5-9f43-7bd76d07b265.gif)

**Comment by RolandPheasant** [comment]
Thanks. I will try and reproduce later

**Comment by MendelMonteiro** [comment]
I think this issue should be re-opened so it doesn't get forgotten

**Comment by RolandPheasant** [comment]
I will try to replicate

**Comment by RolandPheasant** [comment]
@MendelMonteiro I got it at last. Fixed in v0.7 (to be released soon). The position in the bottom viewer was being reset when the underlying file was updated.

The behaviour is: 

-  when you initially show the inline view, it scrolls to line 0
-   when you select an item, it scrolls to that item.
-  when a selected item scrolls of out view, only then does it reset to zero

**Comment by MendelMonteiro** [comment]
Cool, will pull and rebuild

**Comment by RolandPheasant** [comment]
Let me know how it goes, and also check out the new highlight and colour options
