### ISSUE TITLE
Feature request: Save session

### ISSUE THREAD

**Issue by dasjestyr** [RolandPheasant/TailBlazer#63]
The application should have the ability to save a session. That is, any group of logs should be savable as a named group.

Use case:
I have 10 virtual environments that run several components (think development, integration, staging, production, etc), each of which has it's own log file. I need to be able to switch between these sets rapidly as I debug them.

You can see how I implemented it in my log tailer "SwiftTailer" here on github

**Comment by RolandPheasant** [comment]
Obviously this app can never be in the league of swift tailer. Therefore it would be better to recommend the community to use that instead of this.
