### ISSUE TITLE
Feature request: capture selected lines

### ISSUE THREAD

**Issue by dasjestyr** [RolandPheasant/TailBlazer#64]
The application should have the ability to pull out selected log lines into a different window and give me options such as saving the capture to a file, or emailing it, etc.

Use Case:
While debugging (myself or another user of the log tailer), the user may find some useful information that they need to share with someone else, and capturing that should be quick and easy. Think QA using the tailer, or a fellow developer, etc...

You can see how I implemented it in my log tailer "SwiftTailer" here on github.

**Comment by RolandPheasant** [comment]
Obviously this app can never be in the league of swift tailer. Therefore it would be better to recommend the community to use that instead of this.
