### ISSUE TITLE
Feature request: snapshot/import session

### ISSUE THREAD

**Issue by dasjestyr** [RolandPheasant/TailBlazer#65]
The application should have the ability to capture all logs in their current state for all logs currently open in the window.

Use Case:
A multi-component system will have a log for each component in the environment. If an error is encountered, it could be difficult to track down what component caused the error and what all of the variables were that were in play. By snapshotting everything at that moment, the developer can use the tailer to observe the session at the moment of the error. 

A feature that would accompany this would be an "import session" feature where the application could open a zip file contain log file objects and use it to reconstruct a session.

You can see how I implemented it in my log tailer "SwiftTailer" here on github

**Comment by RolandPheasant** [comment]
Obviously this app can never be in the league of swift tailer. Therefore it would be better to recommend the community to use that instead of this.
