### ISSUE TITLE
Filter based on regex

### ISSUE THREAD

**Issue by kstrauss** [RolandPheasant/TailBlazer#67]
A feature request
It would be nice to be able to do filter on a regex expression. Not sure how the UI should evolve as you would need to be able to have both the simple match that is currently done, plus the option of being regex and handling regex parsing errors.

**Comment by RolandPheasant** [comment]
I thought there already was a regex searh request raised but checking through there is not.  This should be done in the near future.

The only reason I have not enabled regex search yet is I have yet to be inspired by how the option should be present.  I will probably do something basic and refine it further down the road

**Comment by RolandPheasant** [comment]
@kstrauss  I have given this a shot. See [release notes](https://github.com/RolandPheasant/TailBlazer/blob/master/Documents/Realease%20v0.6.md). Let me know how you get one

**Comment by kstrauss** [comment]
a simple case seems to work. Thanks definitely helps.
