### ISSUE TITLE
Create persistence store

### ISSUE THREAD

**Issue by RolandPheasant** [RolandPheasant/TailBlazer#7]

**Comment by kmcginnes** [comment]
I'd like to start work on this. What were you thinking for a persistence? Here are some decent options:

* [Akavache](https://github.com/akavache/Akavache)
* [SqlLite](https://github.com/koush/sqlite-net)
* [Json file](http://www.newtonsoft.com/json)

I consider this a toss up between Akavache and Json files. I really like the simplicity of Json files and not needing any big dependencies, but the performance and integration might be better in Akavache.

**Comment by RolandPheasant** [comment]
Keep it simple is definitely the way forward. I  suggest just having an API  to write text to a location. The location then becomes a back end store be it a file location, sqlite or a service.

This enables Json or any other serialization to be used. Personally I like to use xDocument / XmlTextReader which although they require more work up front enable flexible versioning  and reading of old formats without ever stuffing the user up.  

Also it should be a key value pair store.

As for getting started / contribution guidelines I need to get back to you on that. Let me know your thoughts

**Comment by kmcginnes** [comment]
Something like this?

```c#
interface ISettingsStore
{
  Get(string key);
  CreateOrUpdate(string key, object value);
}
```

**Comment by RolandPheasant** [comment]
It's a  good start but I would keep the settings store as some thing which just loads and saves state and don't mix the storing and translation of the objects.

I cannat craft the code as i am typing this on my phone but there would be 2 methods: load and save.

Save would have 2 params: key and state.
Load would have key as a param and will return the state.
State would have 2 props version (int) and value (string)

This way the service is dumb. It just loads and saves which makes it easy to test, easy to replace the backing stored and easier to version check before converting the string back.

It then becomes another concern about what format stuff is stored in.

There is so much more but perhaps it would be easier to continue this on gitter - link on GH home page

**Comment by kmcginnes** [comment]
Sure, I'll jump on after lunch.

**Comment by RolandPheasant** [comment]
Great. I am pleased you want to help.

**Comment by kmcginnes** [comment]
This is what I understood from your message

```c#
interface IStateRepository
{
    void Save(string key, IState state);
    IState Load(string key);
}

interface IState
{
    int Version { get; }
    string Value { get; }
}
```

And what I was thinking originally would play out something like this:

```c#
interface ISettingsStore
{
  Task<object> Get(string key);
  Task CreateOrUpdate(string key, object value);
}

class JsonSettingsStore : ISettingsStore
{
    public JsonSettingsStore(string jsonFilePath) { }

    Task<object> Get(string key)
    {
        // Refresh Json data if the file has changed
        // Find key in the Json document
        // return the value
    }

    Task CreateOrUpdate(string key, object value)
    {
        // Refresh Json data if the file has changed
        // Find key in the Json document
        // Update value if it already exists
        // Create the key and value if it doesn't exist
        // Save the file
    }
}
```

So that would manage the file itself. And then translation would happen in another piece.

```c#
class UserJsonSettingsStore : JsonSettingsStore
{
    public UserJsonSettingsStore() : base(@".\settings.json") { }
}

class UserSettingsLoader
{
    public UserSettingsLoader(UserJsonSettingsStore userSettings)
    {
        _userSettings = userSettings;
    }

    IUserSettings LoadSettings()
    {
        var version = _userSettings.Get("version").AsOrDefault<int>(1);

        var result = new MutableUserSettings();
        result.ShowLineNumbers = _userSettings.Get("showLineNumbers").AsOrDefault<bool>(true);
        // ...
        if (version < 2)
        {
            // we changed from pixel height to point size in version 2 of the settings spec
            var pixelHeight = _userSettings.Get("fontSize").AsOrDefault<double>(14.0);
            result.FontSize = ConvertToPointSize(pixelHeight);
        }
        else
        {
            // already point size
            result.FontSize = _userSettings.Get("fontSize").AsOrDefault<double>(14.0);
        }
    }
}
```

**Comment by RolandPheasant** [comment]
A little different

Check out this folder https://github.com/RolandPheasant/TailBlazer/tree/master/Source/TailBlazer.Domain/Settings for the first bash of the API.

The difference is I split the encoding / decoding with the store. A converter is used for converting from State to object.  Now that may be Jason or anything

Also the store can be SQL Lite or file or service.  I need to get off my pc now so let's catch up tomorrow

**Comment by RolandPheasant** [comment]
Also let's stay away from a settings bucket like user settings and treat the settings on a one by one basis.

**Comment by kmcginnes** [comment]
Sorry for the slow response. As far as storage goes, I'm fine with whatever you want. I'm more interested in how `ISetting` works. What is `T`? Is it an individual setting or a collection of settings?

So the only reason I wanted to pick this up was so that I could implement two of the other issues:
* #8 Recent files
* #52 Save and restore window size and position

If this issue is going to require more design, then I suggest implementing simple versions of the above issues using the standard .net settings store. Then we can implement the true settings store later.

**Comment by RolandPheasant** [comment]
@kmcginnes no worries, I have been completely consumed with getting the performance for very large files up to speed. This has taken an enormous effort and I have had no time to even think about other functionality but thank fully this is done now and  I am very pleased with the results.

Perhaps for the first attempt at settings I am over complicating things but in my industry there are users who may have up to 8 monitors with perhaps up to 10 different apps running with dozens or even hundreds of settings on each system - the one thing they cannot forgive is messed up settings. This influences me! 

My design in based on a couple paradigms.

1. The storing of settings is well abstracted and hidden out of sight of the objects which ultimately consume them.
2. How settings are serialised is flexible and accounts for versioning.
3. The idea behind ISetting<T> is any setting is observable (ignore this for now)
4. State and behaviour must always be kept separate - a mapper takes minutes to write

For version 1 let's keep it simple. As long as we use the state object paradigm then I am happy and can always refine things later.

But I do warn you, the saving and  restoring of layouts will be tricky because the tab control is a fully fledged docking library where the tabs can be docked and pulled out like in google chrome (give it a go to see)

**Comment by RolandPheasant** [comment]
Got the basic concept up and running and to prove the point the system writing and reading recent files which are displayed in the hamburger menu.

@kmcginnes if you look at [RecentFiles.cs](https://github.com/RolandPheasant/TailBlazer/blob/master/Source/TailBlazer.Domain/FileHandling/RecentFiles.cs) and [RecentFilesToStateConverter.cs](https://github.com/RolandPheasant/TailBlazer/blob/master/Source/TailBlazer.Domain/FileHandling/RecentFilesToStateConverter.cs) you will be able to check out the code and see what I meant. The concept is that the consumers are agnostic to the storage. Just the fact that the item is stored or has changed is all I wanted the consumer to be aware of.

The way I implemented achieves that.  Each setting can have its own means of  serialising by implementing it's own  converter.

**Comment by kmcginnes** [comment]
Cool. I'll toy around with this and see if I can implement some other settings. Thanks!

**Comment by RolandPheasant** [comment]
@kmcginnes I have purposely left some code in to show how versioning is handled. If you look, you will see that it is very flexible. The serialisation can change but this is always accompanied with a version check so no excuses for lost settings ever.

I am currently doing some setting for system wide stuff but would be delighted if you could look at the recursive layouts for the docking lib
