### ISSUE TITLE
Case sensitive basic filtering option

### ISSUE THREAD

**Issue by drw112** [RolandPheasant/TailBlazer#72]
Could you provide a check box or option to allow for case sensitive filtering?  This would be helpful when searching for "Error" level log4net messages but ignoring INFO level messages that contain the text "error"

**Comment by RolandPheasant** [comment]
I don't see why not

**Comment by drw112** [comment]
Thank you for implementing this!

**Comment by RolandPheasant** [comment]
You are welcome. I have not released it yet, but if you want a preview you can check out the latest build see [Latest Build](https://ci.appveyor.com/project/RolandPheasant/tailblazer/build/artifacts).
