### ISSUE TITLE
TailBlazer crash and this is the exception.

### ISSUE THREAD

**Issue by yindongfei** [RolandPheasant/TailBlazer#74]
tailblazer is compiled myself yesterday using the latest code from github, it crashes and i got an exception for log file.

2016-01-12 10:35:43,652 ERROR 18 UhandledExceptionHandler index out of range.
argument: index
System.ArgumentOutOfRangeException:  index out of range.
argument: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.Insert(Int32 index, T item)
   在 DynamicData.Internal.ChangeAwareList`1.InsertItem(Int32 index, T item) 位置 C:\projects\dynamicdata-dpbpa\DynamicData\List\Internal\ChangeAwareList.cs:行号 169
   在 DynamicData.Internal.ChangeAwareList`1.Insert(Int32 index, T item) 位置 C:\projects\dynamicdata-dpbpa\DynamicData\List\Internal\ChangeAwareList.cs:行号 296
   在 DynamicData.ListEx.<>c__DisplayClass2_0`2.<Transform>b__0(Change`1 item) 位置 C:\projects\dynamicdata-dpbpa\DynamicData\List\ListEx.cs:行号 150
   在 DynamicData.Kernel.EnumerableEx.ForEach[T](IEnumerable`1 source, Action`1 action) 位置 C:\projects\dynamicdata-dpbpa\DynamicData\Kernel\EnumerableEx.cs:行号 104
   在 DynamicData.ListEx.Transform[TSource,TDestination](IList`1 source, IChangeSet`1 changes, Func`2 transformFactory) 位置 C:\projects\dynamicdata-dpbpa\DynamicData\List\ListEx.cs:行号 143
   在 DynamicData.Internal.Transformer`2.Process(IChangeSet`1 changes) 位置 C:\projects\dynamicdata-dpbpa\DynamicData\List\Internal\Transformer.cs:行号 29
   在 System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   在 System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   在 System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   在 System.Reactive.Linq.ObservableImpl.Do`1._.OnError(Exception error)
   在 System.Reactive.Concurrency.Synchronize`1._.OnError(Exception error)
   在 System.Reactive.Linq.ObservableImpl.Where`1._.OnError(Exception error)
   在 System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   在 System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   在 System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   在 System.Reactive.Linq.ObservableImpl.Scan`2._.OnError(Exception error)
   在 System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   在 System.Reactive.Concurrency.Synchronize`1._.OnNext(TSource value)
   在 System.Reactive.ScheduledObserver`1.Dispatch(ICancelable cancel)
   在 System.Reactive.Concurrency.Scheduler.<ScheduleLongRunning>b__72(Action`1 a, ICancelable c)
   在 System.Reactive.Concurrency.DefaultScheduler.LongRunning.<>c__DisplayClassc`1.<ScheduleLongRunning>b__b(Object arg)
   在 System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c__DisplayClass5.<StartThread>b__4()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by RolandPheasant** [comment]
I have fixed this but it is not released.  Could you grab the latest code, recompile and let me know if you get it again. 

If you do reopen this issue.

**Comment by RolandPheasant** [comment]
BTW if you get the problem again could you also attached the log file which you were using when the crash happened.

This would help me to replicate the issue

**Comment by MendelMonteiro** [comment]
I've just had the same exception - what information would help diagnosing this?  a dump file?

The log file is probably not super useful as it was being written to and is no longer the file that caused the crash

**Comment by RolandPheasant** [comment]
I got the same the other day as well. It is an issue in the dynamic data library (another of my OS projects). I will fix it there. This issue will be my new priority.

**Comment by RolandPheasant** [comment]
@MendelMonteiro I have hopefully fixed the problem in dynamic data now.

To try it out you will need to either build the latest source code or grab the artifacts from the build server (link on readme ).

**Comment by MendelMonteiro** [comment]
Cool, we had also seen this bug in other code which uses DynamicData but we thought it was a bug in the calling code.  It's great to hear that you've fixed this as hopefully now we can stop investigating the other bug.

**Comment by RolandPheasant** [comment]
Fingers crossed that we will not encounter this one again.

**Comment by RolandPheasant** [comment]
If you need to try the latest dynamic data code, see https://github.com/RolandPheasant/DynamicData/issues/23
