### ISSUE TITLE
create new 0.6 release

### ISSUE THREAD

**Issue by CasperTDK** [RolandPheasant/TailBlazer#75]
The current 0.5 is pretty far behind master branch! :)

**Comment by RolandPheasant** [comment]
I am almost done with the regex search and highlighting, after which I will do a release. 

Probably this week

**Comment by CasperTDK** [comment]
Cool!

**Comment by RolandPheasant** [comment]
@CasperTDK  the release will probably be delayed until next week as 

a) I have an issue with dynamic data (another os project) to deal with 
b) In certain conditions reg ex highlighting can be slow.

I will release when these are fixed,

In the meantime if you want something more up to date and are willing to be a guinea pig you can get the latest build here  [Latest Build](https://ci.appveyor.com/project/RolandPheasant/tailblazer/build/artifacts)

**Comment by CasperTDK** [comment]
Thanks. I am using the latest build artifact now and seems to work fine!

**Comment by RolandPheasant** [comment]
Almost there.  Hopefully a release next week - I am just holding back as I want it to be rock solid

**Comment by RolandPheasant** [comment]
@CasperTDK  Done. See [release](https://github.com/RolandPheasant/TailBlazer/blob/master/Documents/Realease%20v0.6.md)
