### ISSUE TITLE
Not a issue:-)

### ISSUE THREAD

**Issue by ghost** [RolandPheasant/TailBlazer#76]
Have been following you and James's work on GIT Hub for a while now. The draggablz control has found an appropriate place in TailBlazer! May I say its an awesome looking (and working too) app.
Why don't you use this as a subject to write some real cool Rx article (I have been looking for something similar for  along time).
I invite you to read my article on MVVM:
http://www.codeproject.com/Articles/753332/XPence-A-WPF-metro-style-smart-client-expense-trac
Its pretty much old now and hardly has anything that the "author of TailBlazer" may find interesting but it surely demonstrates how TalBlazer can be used as a subject for a nice Rx article. What do you think?
-Sid

**Comment by RolandPheasant** [comment]
I have to first of all thank you for the kind words. When I receive positive feedback it really motivates me to make my OS code even better.

I do actually intend to write a blog series about tail blazer and the use of RX within it. I think there should also be at least one article on the use of mvvm and the awesome libraries which TB is based on.

I already have a blog site http://dynamic-data.org/ where I will post to.

**Comment by RolandPheasant** [comment]
I also want to say your article on code project looks brilliant. I have bookmarked it and will read it soon
