### ISSUE TITLE
Scrollbar arrows not working

### ISSUE THREAD

**Issue by YannickMeeus** [RolandPheasant/TailBlazer#77]
Both the vertical and horizontal scrollbar arrows don't seem to actually perform any scrolling.
Also, clicking on a position in the horizontal scrollbar does nothing.

This is on version 0.5.245, installed via Chocolatey.

**Comment by RolandPheasant** [comment]
The arrows work in v0.6. However clicking on the horizontal scroll bar still doesn't work.

I will get this fixed for 0.7

**Comment by YannickMeeus** [comment]
Cool, should have known that it'd be fixed in the dev version. I'll pull it down myself and work against that, just so I don't raise silly things any more.
