### ISSUE TITLE
Different search results should be highlighted in different colors (preferably customizable)

### ISSUE THREAD

**Issue by viswaug** [RolandPheasant/TailBlazer#79]
Use BareTail to view my log files. It has this great feature which lets you to highlight "DEBUG", "WARNING", "ERROR" messages in different color based on different color for different search term. That would be a gerat addition to TailBlazer also.

**Comment by RolandPheasant** [comment]
@viswaug here is a spolier - this will be available in v0.7

![selected highlighting and symbols](https://cloud.githubusercontent.com/assets/9879866/13197315/f7f25866-d7e2-11e5-9a1a-33b9ef3c3e55.gif)

**Comment by mrtaikandi** [comment]
:+1:

**Comment by RolandPheasant** [comment]
Available in v0.7
