### ISSUE TITLE
Show whole source name

### ISSUE THREAD

**Issue by ischas** [RolandPheasant/TailBlazer#82]
Background: I run a service in debug- and release-mode, Both produce a log with the same name, but in different folders.

Suggestion: Show the whole path of a file when you hover over the file name.

**Comment by ischas** [comment]
Okay, my issue isn't really one (at least the background is wrong because the difference in the path is shown), but the suggested feature would still improve this great tool.

**Comment by RolandPheasant** [comment]
I was thinking that I could show it on the bottom bar. Also make the text a hyperlink to open the file / or at least the folder

**Comment by thezim** [comment]
Ran into this last night as well. Had the same log files opened on two different servers and could not tell which was which.

**Comment by RolandPheasant** [comment]
@thezim @ischas Next version, the location will show in the status bar

![filelocation](https://cloud.githubusercontent.com/assets/9879866/13196921/842ba7b4-d7d5-11e5-8e32-3a6fa62709b8.gif)

Also added opens to open the file or folder
