### ISSUE TITLE
Reopen files on start

### ISSUE THREAD

**Issue by kampak1111** [RolandPheasant/TailBlazer#83]
Hi,

It would be useful if TailBlazer at start could open the same files that were opened when it was closed. It sometimes takes a while to open all required files from the Recent files list. Also it could remember where the panel with certain file log was placed, so it opens it exactly as it was before closing application (i.e. one file on left other on right). If the file is not available any more then the panel still should be visible just indicating that the file does not exists (yet usually).

Most of the times I use this type of tools also when developing applications, and that feature would speed it up. The other case is when I use RDP connections so I can easily start TailBlazer and see immediately multiple logs without too much thinking about file names and locations.

Thanks,
Kamil

**Comment by RolandPheasant** [comment]
I had previously made a start on this. 

Will get back on the case soon.

**Comment by RolandPheasant** [comment]
@kampak1111  done on the latest build
