### ISSUE TITLE
Chocolatey install fails

### ISSUE THREAD

**Issue by adamclifford** [RolandPheasant/TailBlazer#87]
When installing TailBlazer from Chocolatey, using the command,  choco install tailblazer the install fails with the following output:-

C:\Users\~>choco install tailblazer
!!ATTENTION!!
The next version of Chocolatey (v0.9.9) will require -y to perform
  behaviors that change state without prompting for confirmation. Start
  using it now in your automated scripts.

  For details on the all new Chocolatey, visit http://bit.ly/new_choco
Chocolatey (v0.9.8.33) is installing 'tailblazer' and dependencies. By installin
g you accept the license for 'tailblazer' and each dependency you are installing
.

tailblazer v0.7.0.360
Uninstalling previous version
Done
Downloading tailblazer 64 bit
  from 'https://github.com/RolandPheasant/TailBlazer/releases/download/0.7.0.360
/TailBlazer_v0.7.0.360.zip'
Extracting C:\Users\~\AppData\Local\Temp\chocolatey\tailblazer\tailblaz
erInstall.zip to C:\ProgramData\chocolatey\lib\tailblazer.0.7.0.360\tools...

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        02/29/2016     08:56            tools
C:\ProgramData\chocolatey\lib\tailblazer.0.7.0.360\tools
tailblazer has finished successfully! The chocolatey gods have answered your req
uest!
Write-Error : Package 'tailblazer v0.7.0.360' did not install successfully: The
 term 'Install-ChocolateyShortcut' is not recognized as the name of a cmdlet, f
unction, script file, or operable program. Check the spelling of the name, or i
f a path was included, verify that the path is correct and try again.
At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:9
0 char:28
+                 Write-Error <<<<  "Package `'$installedPackageName v$installe
dPackageVersion`' did not install successfully: $($_.Exception.Message)"
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

Finished installing 'tailblazer' and dependencies - if errors not shown in conso
le, none detected. Check log for errors if unsure.

**Comment by abuzhynsky** [comment]
@adamclifford You have deprecated version of Chocolatey installed. Chocolatey 0.9.9 was a big [release](https://github.com/chocolatey/choco/wiki/ReleaseNotes#099-march-3-2015) which added new helper function **Install-ChocolateyShortcut**. In your case TailBlazer should be installed but without desktop shortcut. 
Anyway I'd recommend you to update your Chocolatey client to 0.9.9.x version and reinstall TailBlazer.

**Comment by RolandPheasant** [comment]
@adamclifford I am closing this because I assume the comment by @abuzhynsky has solved your problem
