### ISSUE TITLE
Support clearing out the tail window

### ISSUE THREAD

**Issue by jbuedel** [RolandPheasant/TailBlazer#92]
Often while tailblazing some log file, I'll get to a point where I want the old logs out of the way. I go outside Tailblazer and delete or empty the log file manually.  I'd like to be able to clear the file right inside Tailblazer.

I suggest having a way to clear out the tail window, much like I might `clear` out a console window. That is, I click a button or what have you, and the contents of the current tab are removed. Tailing continues from the last line at the time of the clear. ("Clear" need not physically empty out the file. It could though. I don't have a strong opinion either way.)

**Comment by RolandPheasant** [comment]
Funny thing is a work colleague has been asking for this functionality so I will definitely do it

**Comment by rcince** [comment]
Any updates on when this will be available added ?

**Comment by RolandPheasant** [comment]
It will happen. I just happen to have been busy with dynamic data lately and I happen to be on holiday right now.  It will come soonish

**Comment by RolandPheasant** [comment]
Of course, a PR would be welcomed

**Comment by rcince** [comment]
How do I download these updates? I've done a fresh checkout and it doesn't appear to be in there. Thanks.

**Comment by RolandPheasant** [comment]
@rcince you need to get this branch

![image](https://cloud.githubusercontent.com/assets/9879866/14942025/ab3a90da-0fa8-11e6-939e-1b808a2bb3d9.png)

The code is incomplete and has a few bugs but feel free to try it out
