### ISSUE TITLE
Launching tailblazer from command line blocks console usage until it's shutdown

### ISSUE THREAD

**Issue by jbuedel** [RolandPheasant/TailBlazer#93]
I have TailBlazer installed via chocolatey (which I suspect is related to the issue). When I launch `tailblazer` via the command line it blocks the current console until TailBlazer is shutdown.  I'd rather it launch and get out of the way (like `gvim` or `notepad++` does, for instance).

**Comment by RolandPheasant** [comment]
I will take a look

**Comment by abuzhynsky** [comment]
@jbuedel @RolandPheasant I'm Chocolatey package maintainer. The problem exists. I'll fix it in package containing next release.

**Comment by JohannesSchmidt42** [comment]
@jbuedel in your command line just write: 
start tailblazer.exe mylog.txt

**Comment by jbuedel** [comment]
@JohannesSchmidt42 It does as you say, but also leaves a console window hanging around.

**Comment by FilipDeVos** [comment]
To fix the hanging window you need to change your bootstrapper a bit:

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool FreeConsole();

        [STAThread]
        public static void Main(string[] args)
        {
            FreeConsole();

            var app = new App { ShutdownMode = ShutdownMode.OnLastWindowClose };
         ...

**Comment by abuzhynsky** [comment]
Chocolatey package incorrectly generated shim - it was generating console shim instead of gui shim so it was blocking console until TailBlazer is shutdown. Fixed in [0.8.0.464](https://chocolatey.org/packages/tailblazer/0.8.0.464).
