### ISSUE TITLE
Certain file and search combination creates a filter that can't be removed.

### ISSUE THREAD

**Issue by jbuedel** [RolandPheasant/TailBlazer#95]
1. Open [this](https://github.com/chocolatey/choco/blob/master/.gitignore) file from your local disk. (Nothing special about it, just a publicly available file I happen to have on hand.)
1. Click into the search box.
1. Type 5 spaces.  Press Enter
1. Clicking the green X to remove the filter does not remove the filter.

**Comment by RolandPheasant** [comment]
Fixed by #107
